Repository iaebots/iae, pull requests merged in 2021-09, with the labels that each got.

#428 Async image processing
  Dockerfile.dev
  Gemfile
  Gemfile.lock
  app/assets/images/default.png
  app/assets/images/default_cover.png
  app/models/bot.rb
  app/models/developer.rb
  app/models/post.rb
  app/uploaders/avatar_uploader.rb
  app/uploaders/cover_uploader.rb
  app/uploaders/media_uploader.rb
  app/views/bots/_bot.html.erb
  app/views/bots/_bot_simple.html.erb
  app/views/bots/edit.html.erb
  app/views/bots/show.html.erb
  app/views/comments/_comment.html.erb
  app/views/developers/_developer.html.erb
  app/views/developers/registrations/edit.html.erb
  app/views/developers/registrations/new.html.erb
  app/views/developers/show.html.erb
  app/views/layouts/application.html.erb
  app/views/posts/_post.html.erb
  app/workers/promote_job.rb
  config/application.rb
  config/credentials.yml.enc
  config/initializers/shrine.rb
  config/initializers/sidekiq.rb
  config/routes.rb
  db/migrate/20210914014637_add_image_data_columns_for_shrine.rb
  db/migrate/20210914131209_remove_avatar_column.rb
  db/migrate/20210917134520_remove_media_column.rb
  db/migrate/20210920173524_remove_cover_column_from_developers_and_bots.rb
  db/schema.rb
  docker-compose-dev.yml
Labels: enhancement

#430 Shrine I18n
  app/models/concerns/usernames_blocklist.rb
  app/uploaders/avatar_uploader.rb
  app/uploaders/cover_uploader.rb
  config/locales/defaults/en.yml
  config/locales/defaults/pt.yml
  config/locales/models/developer/pt.yml
  config/locales/views/layouts/en.yml
  config/locales/views/layouts/pt.yml
  config/locales/views/pages/home/en.yml
  config/locales/views/pages/home/pt.yml
Labels: enhancement

#431 JS warnings
  app/javascript/packs/custom/timezones.js
  app/views/layouts/application.html.erb
Labels: enhancement

#439 Remove time_ago option for "yesterday at %{time}"
  app/helpers/posts_helper.rb
Labels: bug, High priority

#440 Add extension to uploads without extension based on MIME type
  app/uploaders/avatar_uploader.rb
  app/uploaders/cover_uploader.rb
  app/uploaders/media_uploader.rb
Labels: bug, High priority

#444 Identify whether media is video or image using MIME type
  app/views/posts/_post.html.erb
Labels: bug, High priority

#442 Add correct translation for avatar file field on bots#edit
  app/views/bots/edit.html.erb
Labels: bug, Low priority

#446 fix cover on mobile
  app/assets/stylesheets/application.scss
  app/views/bots/show.html.erb
  app/views/developers/show.html.erb
Labels: bug, enhancement
